print("qual foi a primeira nota?")
numero1 = int(input())
print("qual foi a segunda nota?")
numero2 = int(input())
print("qual foi a terceira nota?")
numero3 = int(input())
print("qual foi a quarta nota?")
numero4 = int(input())
print("resultado foi de :")
print(numero1 + numero2 + numero3 + numero4)
