print("digite a sua idade em anos:")
numero1 = int(input())
print("Qual mês do seu aniversário?:")
numero2 = int(input())
print("Qual dia do seu aniversário?")
numero3 = int(input())
print("Você tem de dias vividos:")
soma1 = (numero1*365) 
soma2 = (numero2*30)
soma3 = (numero3-30)
print (soma1 + soma2 + soma3)