print("digite a sua idade em anos:")
numero1 = int(input())
print("digite a idade em meses:")
numero2 = int(input())
print("Qual dia do seu aniversário?")
numero3 = int(input())
print("Você tem de dias vividos:")
soma1 = (numero1*365) 
soma2 = (numero2*30) 
print(soma1 + soma2 + numero3)